stages:
  - fetch-scripts
  - quality
  - build
  - test
  - deploy
  - analyze

include:
  - project: 'devel/ciscripts'
    file: '.fetch-job.yml'
  - project: 'devel/ciscripts'
    file: .shared-vars.yml
  - 'ci/.gitlab-ci-0-quality-gate.yml'
  - 'ci/.gitlab-ci-1-build.yml'
  - 'ci/.gitlab-ci-2-test.yml'
  - 'ci/.gitlab-ci-3-deploy.yml'
  - 'ci/.gitlab-ci-4-analyze.yml'
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  extends: .shared-variables
  GAMS_CONTAINER_REGISTRY:
      value: registry.gams.com/devel
      description: "URL to the GAMS container registry"
  PF_CUSTOM_BRANCH:
      value: $CUSTOM_BRANCH
      description: "Name of custom branch, or X.Y.Z for published distribution, or 0 if version is specified in text file with lines GAMS_DISTRIB_MAJOR=X, GAMS_DISTRIB_MINOR=Y, GAMS_DISTRIB_GOLD=Z"
  IMAGE_VERSION:
      value: qt6.9.2
      description: "Current Qt image version"
