stages:
  - install-gams # fetch from builds.gams.com or web, all platforms
  - build
  - test
  - deploy # only leg, to github as new release

include: ['ci/.gitlab-ci-install-gams.yml',
          'ci/.gitlab-ci-build.yml',
          'ci/.gitlab-ci-test.yml',
          'ci/.gitlab-ci-deploy.yml']
