test-leg:
  stage: test
  when: on_success
  tags: [linux]
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/leg/builder-qt6.5:latest
    entrypoint: [""]   # prevent startup.sh
  needs: [fetch-prerequisites,build-leg]
  script:
    - GAMS_PATH=/cache/gams-installs/`python3 ci/fetch_gams.py version $PF_CUSTOM_BRANCH $SSH_KEY_PORTING`
    - cd build
    - PATH=$GAMS_PATH:$PATH LD_LIBRARY_PATH="$GAMS_PATH" GMSPYTHONLIB="$GAMS_PATH/GMSPython/lib/libpython3.8.so" gams
    - PATH=$GAMS_PATH:$PATH LD_LIBRARY_PATH="$GAMS_PATH" GMSPYTHONLIB="$GAMS_PATH/GMSPython/lib/libpython3.8.so" ctest --output-on-failure --output-junit leg-results.xml
  artifacts:
    name: unittest-results-leg
    paths: [build/leg-results.xml]
    reports:
      junit: build/leg-results.xml

test-deg:
  stage: test
  when: on_success
  tags: [macos]
  needs: [fetch-prerequisites,build-deg]
  script:
    - GAMS_PATH=$HOME/cache/gams-installs/`python3 ci/fetch_gams.py version $PF_CUSTOM_BRANCH $SSH_KEY_PORTING`
    - cd build
    - PATH=$GAMS_PATH:$PATH DYLD_LIBRARY_PATH=$(pwd)/lib:$GAMS_PATH GMSPYTHONLIB=$GAMS_PATH/GMSPython/lib/libpython3.8.dylib gams
    - PATH=$GAMS_PATH:$PATH DYLD_LIBRARY_PATH=$(pwd)/lib:$GAMS_PATH GMSPYTHONLIB=$GAMS_PATH/GMSPython/lib/libpython3.8.dylib ctest --output-on-failure --output-junit deg-results.xml
  artifacts:
    name: unittest-results-deg
    paths:
      - build/deg-results.xml
    reports:
      junit: build/deg-results.xml

test-dac:
  stage: test
  when: on_success
  tags: [macos-arm64]
  needs: [fetch-prerequisites,build-dac]
  script:
    - GAMS_PATH=$HOME/cache/gams-installs/`python3 ci/fetch_gams.py version $PF_CUSTOM_BRANCH $SSH_KEY_PORTING`
    - cd build
    - PATH=$GAMS_PATH:$PATH DYLD_LIBRARY_PATH=$(pwd)/lib:$GAMS_PATH GMSPYTHONLIB=$GAMS_PATH/GMSPython/lib/libpython3.8.dylib gams
    - PATH=$GAMS_PATH:$PATH DYLD_LIBRARY_PATH=$(pwd)/lib:$GAMS_PATH GMSPYTHONLIB=$GAMS_PATH/GMSPython/lib/libpython3.8.dylib ctest --output-on-failure --output-junit deg-results.xml
  artifacts:
    name: unittest-results-dac
    paths:
      - build/deg-results.xml
    reports:
      junit: build/deg-results.xml

test-wei:
  stage: test
  when: on_success
  tags: [windows]
  image:
    name: $GAMS_CONTAINER_REGISTRY/machines/wei/builder-full:latest
  needs: [install-gamsdist-wei,build-wei]
  script:
    - $gmsdirname = Get-Content mygmsdir.tmp -Raw
    - $GAMS_PATH = "C:\Cache\gams-installs\$gmsdirname"
    - $env:Path = "$GAMS_PATH;$GAMS_PATH\gbin;" + $env:Path
    - $env:GAMSDIR = "$GAMS_PATH;$GAMS_PATH\gbin"
    - findthisgams -q
    - cd build
    - cp bin\Release\gamscpp.dll $GAMS_PATH
    - cp bin\Release\gtest_main.dll $GAMS_PATH
    - cp bin\Release\gtest.dll $GAMS_PATH
    - cp _deps\cpr-build\cpr\Release\cpr.dll $GAMS_PATH
    - cp _deps\curl-build\lib\Release\libcurl.dll $GAMS_PATH
    - cp _deps\zlib-build\Release\zlib.dll $GAMS_PATH
    - gams
    - ctest -V --output-on-failure --output-junit wei-results.xml > ctestlog.txt
  artifacts:
    name: unittest-results-wei
    paths:
      - build/wei-results.xml
    reports:
      junit: build/wei-results.xml
