install-gamsdist-leg:
  extends: .install-gams-leg

install-gamsdist-deg:
  extends: .install-gams-deg

install-gamsdist-dac:
  extends: .install-gams-dac

install-gamsdist-wei:
  extends: .install-gams-wei
