test-leg:
  stage: test
  tags: [linux]
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/leg/builder-${IMAGE_VERSION}:latest
    entrypoint: [""]   # prevent startup.sh
  needs: [fetch-ci-scripts,build-leg]
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-leg]
    - GAMS_PATH=/cache/gams-installs/`cat gams_folder_leg.txt`
    - cd build
    - PATH=$GAMS_PATH:$PATH LD_LIBRARY_PATH="$GAMS_PATH" GMSPYTHONLIB="$GAMS_PATH/GMSPython/lib/libpython3.8.so" gams
    - PATH=$GAMS_PATH:$PATH LD_LIBRARY_PATH="$GAMS_PATH" GMSPYTHONLIB="$GAMS_PATH/GMSPython/lib/libpython3.8.so" ctest --output-on-failure --output-junit leg-results.xml
  artifacts:
    name: unittest-results-leg
    paths: [build/leg-results.xml]
    reports:
      junit: build/leg-results.xml

test-deg:
  stage: test
  tags: [clarus] # set back to macOS once the libcpr issue on carla is fixed
  needs: [fetch-ci-scripts,build-deg]
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-deg]
    - GAMS_PATH=$HOME/cache/gams-installs/`cat gams_folder_deg.txt`
    - cd build
    - PATH=$GAMS_PATH:$PATH DYLD_LIBRARY_PATH=$(pwd)/lib:$GAMS_PATH GMSPYTHONLIB=$GAMS_PATH/GMSPython/lib/libpython3.8.dylib gams
    - PATH=$GAMS_PATH:$PATH DYLD_LIBRARY_PATH=$(pwd)/lib:$GAMS_PATH GMSPYTHONLIB=$GAMS_PATH/GMSPython/lib/libpython3.8.dylib ctest --output-on-failure --output-junit deg-results.xml
  artifacts:
    name: unittest-results-deg
    paths: [build/deg-results.xml]
    reports:
      junit: build/deg-results.xml

test-dac:
  stage: test
  tags: [macos-arm64]
  needs: [fetch-ci-scripts,build-dac]
  script:
    - !reference [.get-gams]
    - !reference [.gams-folder-dac]
    - GAMS_PATH=$HOME/cache/gams-installs/`cat gams_folder_dac.txt`
    - cd build
    - PATH=$GAMS_PATH:$PATH DYLD_LIBRARY_PATH=$(pwd)/lib:$GAMS_PATH GMSPYTHONLIB=$GAMS_PATH/GMSPython/lib/libpython3.8.dylib gams
    - PATH=$GAMS_PATH:$PATH DYLD_LIBRARY_PATH=$(pwd)/lib:$GAMS_PATH GMSPYTHONLIB=$GAMS_PATH/GMSPython/lib/libpython3.8.dylib ctest --output-on-failure --output-junit deg-results.xml
  artifacts:
    name: unittest-results-dac
    paths: [build/deg-results.xml]
    reports:
      junit: build/deg-results.xml

test-wei:
  stage: test
  tags: [windows]
  image:
    name: $MACHINES_CONTAINER_REG/wei/builder-full
  needs: [fetch-ci-scripts,build-wei]
  script:
    - !reference [.get-gams-wei]
    - !reference [.gams-folder-wei]
    - $gmsdirname = Get-Content mygmsdir.tmp -Raw
    - $GAMS_PATH = "C:\Cache\gams-installs\$gmsdirname"
    - $env:Path = "$GAMS_PATH;$GAMS_PATH\gbin;$CI_PROJECT_DIR\build\bin\Release\;$CI_PROJECT_DIR\build\_deps\cpr-build\cpr\Release;$CI_PROJECT_DIR\build\_deps\curl-build\lib\Release;$CI_PROJECT_DIR\build\_deps\zlib-build\Release;" + $env:Path
    - $env:GAMSDIR = "$GAMS_PATH;$GAMS_PATH\gbin"
    - findthisgams -q
    - cd build
    - ctest -V --output-on-failure --output-junit wei-results.xml
  artifacts:
    name: unittest-results-wei
    paths: [build/wei-results.xml]
    reports:
      junit: build/wei-results.xml

secret_detection:
  tags: [linux]
