deploy:
  stage: deploy
  tags: [linux]
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/deployer:latest
    entrypoint: [""]   # prevent startup.sh
  dependencies: []
  rules:
    - if: $CI_COMMIT_TAG =~ /v\d+\.\d+\.\d+.*/
  script:
    - PATH="/opt/github-release:${PATH}"
    - chmod u+x ci/upload-release.sh
    - TAG_NAME=$CI_COMMIT_TAG GITHUB_TOKEN=$GITHUB_TOKEN ./ci/upload-release.sh
